# Learn more about the syntax here:
# https://docs.github.com/en/early-access/github/save-time-with-slash-commands/syntax-for-user-defined-slash-commands
---
trigger: kudos
title: kudos
description: 'Give kudos to your teammates'

surfaces:
  - issue
  - pull_request
  - discussion

steps:
  - type: form
    style: embedded
    body:
      - type: input
        attributes:
          label: User
        validations:
          required: true
      - type: input
        attributes:
          label: Message
        validations:
          required: true
